### ISSUE TITLE
installing the package.

### ISSUE THREAD

**Issue by timknut** [gabraham/plink2R#1]
Hi!
Will this package be installable with 
devtools::install_github("gabraham/plink2R")

**Comment by gabraham** [comment]
Sorry, for some reason I didn't get any notification about this issue.
You should be able to install it via
devtools::install_github("gabraham/plink2R/plink2R")

**Comment by nalnahhas** [comment]
Hi,
I tried to install the package using the command:
devtools::install_github("gabraham/plink2R/plink2R")
But I'm geting an error message:
--------------------------------------------------------
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG    -I"C:/Users/nalnahhas/Documents/R/win-library/3.3/Rcpp/include" -I"C:/Users/nalnahhas/Documents/R/win-library/3.3/RcppEigen/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c data.cpp -o data.o
data.cpp:5:22: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
                      ^
compilation terminated.
make: *** [data.o] Error 1
Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="plink2R.dll" OBJECTS="data.o plink2R.o"' renvoie un statut 2
ERROR: compilation failed for package 'plink2R'
----------------------------------------------------------
I'm using R (latest version) in Rstudio (latest version) on a Windows 10 machine.
RTOOLS V3.4 is also installed on my machine.

Many thanks.

**Comment by gabraham** [comment]
@nalnahhas I've removed the unnecessary dependencies on mmap. Can you install the new version and test it? (I don't have access to Windows at the moment)

**Comment by nalnahhas** [comment]
Hi Gad,

## I tried it. Still not working.

> devtools::install_github("gabraham/plink2R/plink2R")
> Downloading GitHub repo gabraham/plink2R@master
> from URL https://api.github.com/repos/gabraham/plink2R/zipball/master
> Installing plink2R
> "C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/nalnahhas/AppData/Local/Temp/RtmpMBjorB/devtools25427d04a70/gabraham-plink2R-d74be01/plink2R"  \
>   --library="C:/Users/nalnahhas/Documents/R/win-library/3.3" --install-tests 
- installing _source_ package 'plink2R' ...
  *\* libs

**\* arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG    -I"C:/Users/nalnahhas/Documents/R/win-library/3.3/Rcpp/include" -I"C:/Users/nalnahhas/Documents/R/win-library/3.3/RcppEigen/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c data.cpp -o data.o
data.cpp: In constructor 'Data::Data(const char_, const char_, bool)':
data.cpp:9:21: error: 'time' was not declared in this scope
    srand48(time(NULL));
                     ^
data.cpp:9:22: error: 'srand48' was not declared in this scope
    srand48(time(NULL));
                      ^
data.cpp: In member function 'void Data::read_bed(int)':
data.cpp:243:31: error: 'drand48' was not declared in this scope
            double r = drand48();
                               ^
make: **\* [data.o] Error 1
Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="plink2R.dll" OBJECTS="data.o plink2R.o"' renvoie un statut 2
ERROR: compilation failed for package 'plink2R'
- removing 'C:/Users/nalnahhas/Documents/R/win-library/3.3/plink2R'
  Error: Command failed (1)
  --------------------------------------------------------------------------------------
  Many thanks,

Nabeel.

**Comment by veramonlux** [comment]
Were you ever able to resolve this issue? I am running into the same problem

**Comment by StephanieEID** [comment]
I got the same error message when I used the above-mentioned code: devtools::install_github("gabraham/plink2R/plink2R")

**Comment by complexgenome** [comment]
Error : (converted from warning) /tmp/RtmppHDopT/R.INSTALL53314411c2e9/plink2R/man/plink2R-package.Rd:33: All text must be in a section
ERROR: installing Rd objects failed for package ‘plink2R’
 removing ‘/mnt/mfs/../libraries_R/R_LIB4.0/plink2R’
Error: Failed to install 'plink2R' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpCFoLEs/file4ccc32ff7146/plink2R_1.1.tar.gz’ had non-zero exit status

R (v4.0)
devtools_2.3.1

**Comment by irgp2019** [comment]
Hi. 
could anyone fix this ?

**Comment by irgp2019** [comment]
> Error : (converted from warning) /tmp/RtmppHDopT/R.INSTALL53314411c2e9/plink2R/man/plink2R-package.Rd:33: All text must be in a section
> ERROR: installing Rd objects failed for package ‘plink2R’
> removing ‘/mnt/mfs/../libraries_R/R_LIB4.0/plink2R’
> Error: Failed to install 'plink2R' from GitHub:
> (converted from warning) installation of package ‘/tmp/RtmpCFoLEs/file4ccc32ff7146/plink2R_1.1.tar.gz’ had non-zero exit status
> 
> R (v4.0)
> devtools_2.3.1


Hi.
could anyone fix this ?

**Comment by Patricklv** [comment]
[This link](https://zhuanlan.zhihu.com/p/135860286) in Chinese provides a solution that works for me.

I provide a translation of the steps:
1. Download plink2R through git;
2. After unzipping the file,  open plink2R/man/plink2R-package.Rd and move line 33-34 into {} as shown below:

```
\references{
~~ Literature or other references for background information ~~
~~ Optionally other standard keywords, one per line, from file KEYWORDS in ~~
~~ the R documentation directory ~~}
```
3. Open plink2R/src/data.cpp and insert the following at the very beginning of the file:
```
#include <sys/time.h> 
#include <stdlib.h> 
#define srand48(x) srand((int)(x)) 
#define drand48() ((double)rand()/(RAND_MAX + 1.0))
```
4. Install through `devtools::install_local('C:/cygwin64/home/xxx/fusion_twas-master/plink2R-master/plink2R/')`.

IF still run into error, check if some relevant package, such as Rcpp, is not updated.
