### ISSUE TITLE
Read_Plink crashes for data set with 637000 SNPs

### ISSUE THREAD

**Issue by jrahimik** [gabraham/plink2R#3]
Hi,

I am using Read_Plink to read a data set of 637000 SNPs and 6000 individuals. The packages installed fine, however when I am trying to run Read_Plink R crashes. I have tried to the code on a machine with RAM of 32 GB and same thing happens. Really appreciate if you can help me with the issue.

Thanks,
Javad Rahimikollu

**Comment by gabraham** [comment]
@jrahimik not sure what the issue is, but there are other R packages that can read large plink files, e.g. https://cran.r-project.org/web/packages/BEDMatrix/
