### ISSUE TITLE
ERROR: compilation failed for package 'plink2R'

### ISSUE THREAD

**Issue by jielab** [gabraham/plink2R#9]
Hi, there:

Please see the screenshot below, I could NOT install this package into my Windows R 3.6.2.

Can someone please help me to resolve this bug?

Thank you very much & best regards,
Jie

![screenshot](https://user-images.githubusercontent.com/26947455/72094231-e45e3180-3350-11ea-8047-dbb00d7c3049.JPG)

**Comment by gabraham** [comment]
Hi @jiehuang001 
Sorry but plink2R isn't supported on Windows, because the C++ code depends on some Unix-specific functions. Have a look at https://github.com/QuantGen/BEDMatrix for an alternative.
 
Gad

**Comment by jielab** [comment]
I actually made the following change and now it works for Window!!!
So, can you please implement the following so that others could use PLINK2R for Windows?


# Changes(For Windows):
## 1. plink2R/plink2R/plink2R-package.Rd: move 33-34 lines into brace
32-34:
~~ Optionally other standard keywords, one per line, from file KEYWORDS in ~~
~~ the R documentation directory ~~
}

## 2. plink2R/plink2R/src/data.cpp: 
import time.h and stdlib.h and use the random replaces srand48 and drand48 (these functions are not in the standard library in windows)
Add:  
#include <sys/time.h>
#include <stdlib.h>
#define srand48(x) srand((int)(x))
#define drand48() ((double)rand()/(RAND_MAX + 1.0))


# Installation:
## clone the plink2R from github: https://github.com/gabraham/plink2R.git
## alter the scripts accordingly
install.packages(c("Rcpp", "RcppEigen")
if (!require("devtools")) {install.packages("devtools"}
library("devtools")
install_local('./plink2R/')
